# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.synced_folder "../", "/home/vagrant/dmas"
  config.ssh.forward_x11 = true

  config.vm.box = "ktr/mininet"
  config.vm.box_version = "1.1.0"

  # Currently use a private IP for the box
  config.vm.network :private_network, ip: "192.168.0.110"

   # Access through a GUI 
   config.vm.provider "virtualbox" do |v|
     v.name = "KTR-Mininet"
     v.gui = false
     v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
     v.customize ["modifyvm", :id, "--cpus", "2"]
     v.customize ["modifyvm", :id, "--memory", "2048"]
     # Internet access
     v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    rm -r /home/vagrant/pox/ext
    ln -s /home/vagrant/dmas/pox/ext /home/vagrant/pox/ext
    sudo sh /home/vagrant/dmas/vagrant-box/scripts/smtp_server.sh
    sudo sh /home/vagrant/dmas/vagrant-box/scripts/mail_scanner.sh
  SHELL
end